[package]
name = "cinnamos-kernel"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "cinnamos-kernel"
test = false
bench = false

[lib]
test = false
bench = false

[dependencies]
cinnamos-abi = { path = "../cinnamos-abi" }
structs = { path = "../structs" }
riscv = { version = "0.16", features = ["s-mode"] }
bitflags = "2.13"
sbi = "0.3"
fdt = "0.1"
spin = "0.12"
uart = { version = "3.0", default-features = false, features = ["address_impl"] }

log = "0.4"
pastey = "0.2"
